package net.piinut.voidophobia.item;

import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.piinut.voidophobia.Voidophobia;
import net.piinut.voidophobia.block.ModBlocks;
import net.piinut.voidophobia.entity.ModEntities;
import net.piinut.voidophobia.item.tool.*;


public class ModItems {

    public static final ItemGroup VOIDOPHOBIA_DEFAULT_GROUP = FabricItemGroupBuilder.build(
            new Identifier(Voidophobia.MODID, "default"),
            () -> new ItemStack(ModBlocks.GODEL_CRYSTAL_BLOCK));

    public static final BlockItem SLIGHTLY_CRACKED_BEDROCK_ITEM = new BlockItem(ModBlocks.SLIGHTLY_CRACKED_BEDROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem GODEL_CRYSTAL_ITEM = new BlockItem(ModBlocks.GODEL_CRYSTAL_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem WEAK_ARTIFICIAL_BEDROCK_ITEM = new BlockItem(ModBlocks.WEAK_ARTIFICIAL_BEDROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem BASIC_VUXDUCT_ITEM = new BlockItem(ModBlocks.BASIC_VUXDUCT, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem VUX_LAMP_ITEM = new BlockItem(ModBlocks.VUX_LAMP, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem ETERNAL_FIRE_ITEM = new BlockItem(ModBlocks.ETERNAL_FIRE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem REINFORCED_PISTON_ITEM = new BlockItem(ModBlocks.REINFORCED_PISTON, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem REINFORCED_STICKY_PISTON_ITEM = new BlockItem(ModBlocks.REINFORCED_STICKY_PISTON, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem COMPACT_NETHER_PORTAL_ITEM = new BlockItem(ModBlocks.COMPACT_NETHER_PORTAL, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem ITEM_TDI_ITEM = new BlockItem(ModBlocks.ITEM_TDI, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem AZURE_SAND_ITEM = new BlockItem(ModBlocks.AZURE_SAND, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem AZURE_SANDSTONE_ITEM = new BlockItem(ModBlocks.AZURE_SANDSTONE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem AZURE_SANDSTONE_BRICKS_ITEM = new BlockItem(ModBlocks.AZURE_SANDSTONE_BRICKS, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem STARDUST_BLOCK_ITEM = new BlockItem(ModBlocks.BLOCK_OF_STARDUST, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem STARROCK_ITEM = new BlockItem(ModBlocks.STARROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem STARROCK_BRICKS_BLOCK_ITEM = new BlockItem(ModBlocks.STARROCK_BRICKS, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem CHROME_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.CHROME_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem DEEPSLATE_CHROME_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.DEEPSLATE_CHROME_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem RAW_CHROME_BLOCK_ITEM = new BlockItem(ModBlocks.RAW_CHROME_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem NICKEL_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.NICKEL_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem DEEPSLATE_NICKEL_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.DEEPSLATE_NICKEL_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem RAW_NICKEL_BLOCK = new BlockItem(ModBlocks.RAW_NICKEL_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem ALLOY_FURNACE_BLOCK = new BlockItem(ModBlocks.ALLOY_FURNACE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem STAINLESS_STEEL_BLOCK = new BlockItem(ModBlocks.STAINLESS_STEEL_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem VUX_MACHINE_CORE_BLOCK_ITEM = new BlockItem(ModBlocks.VUX_MACHINE_CORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem VUX_FORMING_MACHINE = new BlockItem(ModBlocks.VUX_FORMING_MACHINE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem LASER_ENGRAVING_MACHINE = new BlockItem(ModBlocks.LASER_ENGRAVING_MACHINE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem VUX_FILTER_MACHINE_BLOCK_ITEM = new BlockItem(ModBlocks.VUX_FILTER_MACHINE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem COMPRESSED_NETHER_BRICKS_BLOCK_ITEM = new BlockItem(ModBlocks.COMPRESSED_NETHER_BRICKS, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem CREATIVE_CRACKED_BEDROCK_BLOCK_ITEM = new BlockItem(ModBlocks.CREATIVE_CRACKED_BEDROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem VACUUM_COATER = new BlockItem(ModBlocks.VACUUM_COATER, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem STRONG_ARTIFICIAL_BEDROCK_BLOCK_ITEM = new BlockItem(ModBlocks.STRONG_ARTIFICIAL_BEDROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem SILVER_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.SILVER_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem DEEPSLATE_SILVER_ORE_BLOCK_ITEM = new BlockItem(ModBlocks.DEEPSLATE_SILVER_ORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem CRACKED_BEDROCK_BLOCK_ITEM = new BlockItem(ModBlocks.CRACKED_BEDROCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem NICKEL_BLOCK_ITEM = new BlockItem(ModBlocks.NICKEL_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem CHROME_BLOCK_ITEM = new BlockItem(ModBlocks.CHROME_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem SILVER_BLOCK_ITEM = new BlockItem(ModBlocks.SILVER_BLOCK, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem REINFORCED_GLASS = new BlockItem(ModBlocks.REINFORCED_GLASS, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem BLAST_CHAMBER = new BlockItem(ModBlocks.BLAST_CHAMBER, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem LASER_TRANSMITTER = new BlockItem(ModBlocks.LASER_TRANSMITTER, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem END_SAND = new BlockItem(ModBlocks.END_SAND, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final BlockItem PRECISION_VUX_MACHINE_CORE_BLOCK_ITEM = new BlockItem(ModBlocks.PRECISION_VUX_MACHINE_CORE, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUX_METER = new VuxMeterItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item GODEL_CRYSTAL_SHARD = new GodelCrystalShardItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ARTIFICIAL_BEDROCK_SCRAP = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item PARADOXIUM = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item COMPACT_PORTAL_LINKER = new CompactPortalLinkerItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(1));
    public static final Item INFERNIUM = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item LEVITATIUM = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item STARDUST = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ETHER_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item RAW_CHROME = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item CHROME_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item RAW_NICKEL = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item NICKEL_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item RESONATING_QUARTZ = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item NICHROME_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item STAINLESS_STEEL_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VPU_CHIP = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUXIN = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUXOUT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUX_LASER_COMPONENT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUX_FILTER_TEMPLATE = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VUX_FILTER = new VuxFilterItem(new FabricItemSettings().maxCount(1).maxDamage(64));
    public static final Item WEAK_VUX_VALVE = new AbstractVuxValveItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item NICHROME_WIRE = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item BASIC_HEATING_COIL = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ADVANCED_HEATING_COIL = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item VACUUM_PUMP = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item COPPER_NUGGET = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item AMETHYST_LENS = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_COATED_AMETHYST_SHARD = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item RAW_SILVER = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item INVAR_INGOT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item REDSTONE_QUARTZ = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item MODIFIER_MODULE_TEMPLATE = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item BASIC_MODIFIER_MODULE = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item DELICATE_FILTERING_MODIFIER_MODULE = new ModifierModuleItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(1), "delicate_filtering", 2, 1);
    public static final Item PROCESSING_SPEED_BOOST_MODIFIER_MODULE = new ModifierModuleItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(1), "processing_speed_boost", 1, 1);
    public static final Item VUX_CAPACITY_UPGRADE_MODIFIER_MODULE = new ModifierModuleItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(1), "vux_capacity_upgrade", 1, 0);
    public static final Item CHROME_NICKEL_BLEND = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item COOLING_PAD = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ABYSS_SPIDER_SPAWN_EGG = new SpawnEggItem(ModEntities.ABYSS_SPIDER, 2103108,11183552, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ABYSS_SPIDER_FANG = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ENSORCELLED_SPAWN_EGG = new SpawnEggItem(ModEntities.ENSORCELLED, 2115459, 14419, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ENSORCELLED_ROTTEN_FLESH = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).food(new FoodComponent.Builder().hunger(4).saturationModifier(0.1f).statusEffect(new StatusEffectInstance(StatusEffects.HUNGER, 600, 0), 0.8f).meat().build()));
    public static final Item PARADOXIUM_DUST = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item ENSORCELLED_PARADOXIUM_DUST = new EnsorcelldParadoxiumDustItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_SWORD = new SilverSwordItem(3, -2.4f, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_PICKAXE = new ModPickaxeItem(SilverToolMaterial.INSTANCE, 1, -2.8f, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_SHOVEL = new ShovelItem(SilverToolMaterial.INSTANCE, 1.5f, -3.0f, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_AXE = new SilverAxeItem(6, -3f, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item SILVER_HOE = new ModHoeItem(SilverToolMaterial.INSTANCE, 0, -3.0f, new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item REFINED_NETHER_DUST = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item NETHER_ROD = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    public static final Item POTION_OF_BLINDNESS_IN_SILVER_BOTTLE = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(16));
    public static final Item BOTTLE_OF_SHADOW = new BottleOfShadowItem(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP).maxCount(16));
    public static final Item ACTIVATION_LASER_LENS = new LaserLensItem(12);
    public static final Item BURNING_LASER_LENS = new LaserLensItem(12);
    public static final Item DESTRUCTION_LASER_LENS = new LaserLensItem(6);
    public static final Item ENHANCED_VUX_LASER_COMPONENT = new Item(new FabricItemSettings().group(VOIDOPHOBIA_DEFAULT_GROUP));
    private static void register(Item item, String id){
        Registry.register(Registry.ITEM, new Identifier(Voidophobia.MODID, id), item);
    }

    public static void registerAll(){
        register(SLIGHTLY_CRACKED_BEDROCK_ITEM, "slightly_cracked_bedrock");
        register(CRACKED_BEDROCK_BLOCK_ITEM, "cracked_bedrock");
        register(CREATIVE_CRACKED_BEDROCK_BLOCK_ITEM, "creative_cracked_bedrock");
        register(GODEL_CRYSTAL_ITEM, "godel_crystal_block");
        register(GODEL_CRYSTAL_SHARD, "godel_crystal_shard");
        register(ARTIFICIAL_BEDROCK_SCRAP, "artificial_bedrock_scrap");
        register(WEAK_ARTIFICIAL_BEDROCK_ITEM, "weak_artificial_bedrock");
        register(BASIC_VUXDUCT_ITEM, "basic_vuxduct");
        register(VUX_LAMP_ITEM, "vux_lamp");
        register(REINFORCED_PISTON_ITEM, "reinforced_piston");
        register(REINFORCED_STICKY_PISTON_ITEM, "reinforced_sticky_piston");
        register(ETERNAL_FIRE_ITEM, "eternal_fire");
        register(COMPACT_NETHER_PORTAL_ITEM, "compact_nether_portal");
        register(ITEM_TDI_ITEM, "item_tdi");
        register(COMPACT_PORTAL_LINKER, "portal_linker");
        register(VUX_METER, "vux_meter");
        register(PARADOXIUM, "paradoxium");
        register(LEVITATIUM, "levitatium");
        register(ETHER_INGOT, "ether_ingot");
        register(CHROME_ORE_BLOCK_ITEM, "chrome_ore");
        register(DEEPSLATE_CHROME_ORE_BLOCK_ITEM, "deepslate_chrome_ore");
        register(RAW_CHROME, "raw_chrome");
        register(RAW_CHROME_BLOCK_ITEM, "raw_chrome_block");
        register(CHROME_INGOT, "chrome_ingot");
        register(CHROME_BLOCK_ITEM, "chrome_block");
        register(NICKEL_ORE_BLOCK_ITEM, "nickel_ore");
        register(DEEPSLATE_NICKEL_ORE_BLOCK_ITEM, "deepslate_nickel_ore");
        register(RAW_NICKEL, "raw_nickel");
        register(RAW_NICKEL_BLOCK, "raw_nickel_block");
        register(NICKEL_INGOT, "nickel_ingot");
        register(NICKEL_BLOCK_ITEM, "nickel_block");
        register(RESONATING_QUARTZ, "resonating_quartz");
        register(ALLOY_FURNACE_BLOCK, "alloy_furnace");
        register(NICHROME_INGOT, "nichrome_ingot");
        register(CHROME_NICKEL_BLEND, "chrome_nickel_blend");
        register(STAINLESS_STEEL_INGOT, "stainless_steel_ingot");
        register(STAINLESS_STEEL_BLOCK, "stainless_steel_block");
        register(VPU_CHIP, "vpu_chip");
        register(VUXIN, "vuxin");
        register(VUXOUT, "vuxout");
        register(VUX_LASER_COMPONENT, "vux_laser_component");
        register(ENHANCED_VUX_LASER_COMPONENT, "enhanced_vux_laser_component");
        register(VUX_MACHINE_CORE_BLOCK_ITEM, "vux_machine_core");
        register(PRECISION_VUX_MACHINE_CORE_BLOCK_ITEM, "precision_vux_machine_core");
        register(VUX_FORMING_MACHINE, "vux_forming_machine");
        register(VUX_FILTER_TEMPLATE, "vux_filter_template");
        register(VUX_FILTER, "vux_filter");
        register(LASER_ENGRAVING_MACHINE, "laser_engraving_machine");
        register(WEAK_VUX_VALVE, "weak_vux_valve");
        register(VUX_FILTER_MACHINE_BLOCK_ITEM, "vux_filter_machine");
        register(COMPRESSED_NETHER_BRICKS_BLOCK_ITEM, "compressed_nether_bricks");
        register(REFINED_NETHER_DUST, "refined_nether_dust");
        register(INFERNIUM, "infernium");
        register(NICHROME_WIRE, "nichrome_wire");
        register(BASIC_HEATING_COIL, "basic_heating_coil");
        register(ADVANCED_HEATING_COIL, "advanced_heating_coil");
        register(VACUUM_PUMP, "vacuum_pump");
        register(VACUUM_COATER, "vacuum_coater");
        register(STRONG_ARTIFICIAL_BEDROCK_BLOCK_ITEM, "strong_artificial_bedrock");
        register(COPPER_NUGGET, "copper_nugget");
        register(AMETHYST_LENS, "amethyst_lens");
        register(SILVER_COATED_AMETHYST_SHARD, "silver_coated_amethyst_shard");
        register(RAW_SILVER, "raw_silver");
        register(SILVER_INGOT, "silver_ingot");
        register(SILVER_BLOCK_ITEM, "silver_block");
        register(SILVER_ORE_BLOCK_ITEM, "silver_ore");
        register(DEEPSLATE_SILVER_ORE_BLOCK_ITEM, "deepslate_silver_ore");
        register(SILVER_PICKAXE, "silver_pickaxe");
        register(SILVER_AXE, "silver_axe");
        register(SILVER_SHOVEL, "silver_shovel");
        register(SILVER_SWORD, "silver_sword");
        register(SILVER_HOE, "silver_hoe");
        register(INVAR_INGOT, "invar_ingot");
        register(REDSTONE_QUARTZ, "redstone_quartz");
        register(MODIFIER_MODULE_TEMPLATE, "modifier_module_template");
        register(BASIC_MODIFIER_MODULE, "basic_modifier_module");
        register(DELICATE_FILTERING_MODIFIER_MODULE, "delicate_filtering_modifier_module");
        register(PROCESSING_SPEED_BOOST_MODIFIER_MODULE, "processing_speed_boost_modifier_module");
        register(VUX_CAPACITY_UPGRADE_MODIFIER_MODULE, "vux_capacity_upgrade_modifier_module");
        register(COOLING_PAD, "cooling_pad");
        register(ENSORCELLED_SPAWN_EGG, "ensorcelled_spawn_egg");
        register(ENSORCELLED_ROTTEN_FLESH, "ensorcelled_rotten_flesh");
        register(ABYSS_SPIDER_SPAWN_EGG, "abyss_spider_spawn_egg");
        register(ABYSS_SPIDER_FANG, "abyss_spider_fang");
        register(PARADOXIUM_DUST, "paradoxium_dust");
        register(ENSORCELLED_PARADOXIUM_DUST, "ensorcelled_paradoxium_dust");
        register(REINFORCED_GLASS, "reinforced_glass");
        register(BLAST_CHAMBER, "blast_chamber");
        register(NETHER_ROD, "nether_rod");
        register(POTION_OF_BLINDNESS_IN_SILVER_BOTTLE, "potion_of_blindness_in_silver_bottle");
        register(BOTTLE_OF_SHADOW, "bottle_of_shadow");
        register(LASER_TRANSMITTER, "laser_transmitter");
        register(ACTIVATION_LASER_LENS, "activation_laser_lens");
        register(BURNING_LASER_LENS, "burning_laser_lens");
        register(DESTRUCTION_LASER_LENS, "destruction_laser_lens");
        register(END_SAND, "end_sand");
        register(STARDUST, "stardust");
        register(STARDUST_BLOCK_ITEM, "block_of_stardust");
        register(STARROCK_ITEM, "starrock");
        register(STARROCK_BRICKS_BLOCK_ITEM, "starrock_bricks");
        register(AZURE_SAND_ITEM, "azure_sand");
        register(AZURE_SANDSTONE_ITEM, "azure_sandstone");
        register(AZURE_SANDSTONE_BRICKS_ITEM, "azure_sandstone_bricks");
    }

}
